In [1]:
import numpy as np

## Datatypes and Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1,2,3], [4,5.0,6.6]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [7]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.6]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.size

3

In [14]:
type(a1)

numpy.ndarray

In [15]:
# Create a dataframe form numpy array
import pandas as pd

df = pd.DataFramea(a2)

AttributeError: module 'pandas' has no attribute 'DataFramea'

In [16]:
df = pd.DataFrame(a2)

In [17]:
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.6

# creating numpy arrays

In [18]:
sample_array = np.array([1,2,3])

In [19]:
sample_array

array([1, 2, 3])

In [21]:
ones = np.ones((2,3))

In [22]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
ones.dtype

dtype('float64')

In [24]:
zeros = np.zeros((2,3))

In [25]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0, 10, 2)

In [27]:
range_array

array([0, 2, 4, 6, 8])

In [29]:
random_array = np.random.randint(0, 10, size=(3,5))

In [30]:
random_array

array([[4, 0, 0, 7, 2],
       [6, 9, 3, 4, 8],
       [9, 8, 3, 2, 9]])

In [31]:
random_array.size

15

In [32]:
random_array.shape

(3, 5)

In [36]:
random_array2 = np.random.random((5,3))

In [37]:
random_array2

array([[0.9881466 , 0.86048761, 0.02708542],
       [0.10255673, 0.22107643, 0.96960133],
       [0.18193136, 0.57506596, 0.08001582],
       [0.71204457, 0.69536552, 0.76555429],
       [0.69456084, 0.9918263 , 0.79930924]])

In [38]:
random_array3 = np.random.rand(5,3)

In [39]:
random_array3

array([[0.74159791, 0.93502058, 0.4706367 ],
       [0.08745942, 0.98210079, 0.75857014],
       [0.28388875, 0.80853271, 0.5369036 ],
       [0.24808384, 0.21538337, 0.32557017],
       [0.21955214, 0.81694497, 0.55055737]])

In [42]:
# Pseudo-random numbers
#np.random.seed()
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[1, 4, 4],
       [5, 4, 6],
       [9, 2, 8],
       [6, 1, 7],
       [8, 0, 1]])